### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by LasseSLambertsen** [fwestenberg/reolink_dev#264]
**Describe the bug**
Using newest master commit, the following error results in a the integration not being setup:
```
File "/config/custom_components/reolink_dev/camera.py", line 91, in <module>
    class ReolinkCamera(ReolinkEntity, Camera):
  File "/config/custom_components/reolink_dev/camera.py", line 213, in ReolinkCamera
    self, width: int | None = None, height: int | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
````

**Comment by dannyvanderzande** [comment]
I can confirm this behaviour. 

I updated to master branch because of the H265 references which I need for high res video quality from my camera.  I then setup my camera as following
![image](https://user-images.githubusercontent.com/835479/133480880-ab3f1b21-5ea5-4bfe-8f0b-bfec45d9f516.png)

Maybe this info is useful for resolving this error. Either way, keep up the good work!

**Comment by fwestenberg** [comment]
This should be fixed in the latest release. Unfortunately I found out about this issue too late and had to delete release v0.20. Please reinstall this update.

**Comment by dannyvanderzande** [comment]
There is definitely an improvement but this does not seem to fix all of the problems I am experiencing. On my phone I can see the camera feed but on my pc (Chrome/Windows 10) it will not load properly..
